Package { #name : #OCompiler,
	#classes : [
		'OptimizingCSSATransformer',
		'OptimizingBraunAssigner',
		'OptimizingCodeEmitter',
		'OptimizingMethodInliner',
		'OptimizingNativizer',
		'OptimizingInstructionFragmenter',
		'OptimizingInstructionSelector',
		'OptimizingPhiSimplification',
		'OptimizingRegisterAllocator',
		'OptimizingVariableBinder',
		'OptimizingCFGSimplifier',
		'OptimizingSSAReconstructor',
		'OptimizingVisitor',
		'OptimizingLivenessAnalysis',
		'OptimizingBraunAllocator',
		'OptimizingValueNumbering',
		'OptimizingBlockInliner',
		'OptimizingUsesVerifier',
		'OptimizingTwoAddressEnforcer'
	]
}

