"
    Copyright (c) 2020 Aucerna.
	Copyright (c) 2009-2018 Stefan Marr <git@stefan-marr.de>
    See license in root and /Performance/Benchmarks directories.
"

Package { #name : #Tests,
	#classes : [
		'SMarkAutosizeRunnerTest',
		'SMarkHarnessArgumentParserTest',
		'SMarkHarnessClassTest',
		'SMarkReporterTest',
		'SMarkResultTest',
		'SMarkRunnerTest',
		'SMarkSuiteTest',
		'SMarkTest',
		'SMarkTestAutosizeRunner',
		'SMarkTestRunner',
		'SMarkTestRunnerSuite',
		'SMarkTestRunnerSuiteForAutosizing',
		'SMarkTestRunnerSuiteForPerfromBenchmark',
		'SMarkTestSuite',
		'SMarkTestSuiteWithBaseBenchmark',
		'SMarkTestWeakScalingRunner',
		'SMarkTimerTest',
		'SMarkWeakScalingRunnerTest'
	]
}

