Package { #name : #Tests,
	#classes : [
		'SMarkAutosizeRunnerTest',
		'SMarkHarnessArgumentParserTest',
		'SMarkHarnessClassTest',
		'SMarkReporterTest',
		'SMarkResultTest',
		'SMarkRunnerTest',
		'SMarkSuiteTest'
		'SMarkTestRunner',
		'SMarkTest',
		'SMarkTestAutosizeRunner',
		'SMarkTestRunnerSuite',
		'SMarkTestRunnerSuiteForAutosizing',
		'SMarkTestRunnerSuiteForPerfromBenchmark',
		'SMarkTestSuite',
		'SMarkTestSuiteWithBaseBenchmark',
		'SMarkTestWeakScalingRunner',
		'SMarkTimerTest',
		'SMarkWeakScalingRunnerTest'
	]
}

