"
	Copyright (c) 2021 Aucerna.
	See (MIT) license in root directory.
"

Package { 
	#name : #GUIbase,
	#requires : [
		'CommonControls',
		'GDI',
		'SKernel',
		'SUnit',
		'WindowsSystem'
	]
	#classes : [
		'ARGBColor',
		'Bitmap',
		'BitmapPool',
		'BottomCoordinate',
		'Brush',
		'BrushFillType',
		'Color',
		'Drawer',
		'FrameCoordinate',
		'FramingLayout',
		'FramingLayoutTest',
		'GradientFillType',
		'GUIControlItem',
		'HatchFillType',
		'HeaderItem',
		'HorizontalCoordinate',
		'LeftCoordinate',
		'LinearGradientFillType',
		'ListItem',
		'PathGradientFillType',
		'Pen',
		'Pencil',
		'PencilCase',
		'RadialGradientFillType',
		'RGBColor',
		'RightCoordinate',
		'SolidFillType',
		'TopCoordinate',
		'TreeItem',
		'VerticalCoordinate'
	]
}

