"
    Copyright (c) 2020 Aucerna.
	Copyright (c) 2009-2018 Stefan Marr <git@stefan-marr.de>
    See license in root and /Performance/Benchmarks directories.
"

Package { #name : #Suites,
	#classes : [
		'SMarkBenchmarkGame',
		'SMarkCompiler',
		'SMarkCompilerTargetClass',
		'SMarkDeltaBlue',
		'SMarkHighLevel',
		'SMarkLoops',
		'SMarkMediumLevel',
		'SMarkRichards',
		'SMarkSlopstone',
		'SMarkSmopstone'
	]
}

