"
    Copyright (c) 2020 Aucerna. 
    Copyright (c) 2008-2019 The Pharo Project, and Contributors.
    See (MIT) license in root directory.
"

Package { #name : #Nodes,
	#classes : [
		'PPXmlAttribute',
		'PPXmlComment',
		'PPXmlData',
		'PPXmlDoctype',
		'PPXmlDocument',
		'PPXmlElement',
		'PPXmlMacro',
		'PPXmlName',
		'PPXmlNode',
		'PPXmlParent',
		'PPXmlProcessing',
		'PPXmlText',
		'XmlFormattingVisitor',
		'XmlNodeVisitor',
		'XmlPaintingVisitor'
	]
}

