"
	Copyright (c) 2021 Aucerna.
	See (MIT) license in root directory.
"

Package { 
	#name : #GDIPlus,
	#requires : [
		'extensions-gui',
		'GUIbase',
		'Kernel',
		'Utilities'
	]
	#classes : [
		'ARGB',
		'BitmapData',
		'ColorMatrix',
		'ColorPalette',
		'EncoderParameter',
		'EncoderParameters',
		'GDIPlusAdjustableArrowCap',
		'GDIPlusBitmap',
		'GDIPlusBrush',
		'GDIPlusCachedBitmap',
		'GDIPlusCustomLineCap',
		'GDIPlusDLL',
		'GDIPlusDrawer',
		'GDIPlusError',
		'GDIPlusFont',
		'GDIPlusFontCollection',
		'GDIPlusFontFamily',
		'GDIPlusGraphics',
		'GDIPlusGraphicsPath',
		'GDIPlusGraphicsPathIterator',
		'GDIPlusHatchBrush',
		'GDIPlusImage',
		'GDIPlusImageAttributes',
		'GDIPlusInstalledFontCollection',
		'GDIPlusLinearGradientBrush',
		'GDIPlusMatrix',
		'GDIPlusMeasureStringResult',
		'GDIPlusMetafile',
		'GDIPlusObject',
		'GDIPlusPathGradientBrush',
		'GDIPlusPen',
		'GDIPlusPrivateFontCollection',
		'GDIPlusRegion',
		'GDIPlusSolidBrush',
		'GdiplusStartupInput',
		'GDIPlusStringFormat',
		'GdiPlusStructure',
		'GDIPlusTextureBrush',
		'HueSaturationLightnessParams',
		'ImageCodecInfo',
		'PointF',
		'PropertyItem',
		'RectF'
	]
}

