Package { #name : #C,
	#classes : [
		'ArrayStructField',
		'BitmapStructField',
		'CArgumentField',
		'CBasicType',
		'CEnum',
		'CPointerType',
		'CStatementList',
		'CStruct',
		'CStructField',
		'CTranslationUnit',
		'CType',
		'CTypedef',
		'CUnion',
		'CUnresolvedType',
		'FFIDeclaration',
		'FFIDeclarationTest',
		'FFIDefinitionsBrowser',
		'FFISendersModel',
		'OffsetDictionaryWriter',
		'SingleStructField',
		'TypedefGrammar',
		'TypedefParser',
		'TypedefParserTest'
	]
}

