"
	Copyright (c) 2021 Aucerna.
	See (MIT) license in root directory.
"

Package { 
	#name : #GDI,
	#requires : [
		'GUIbase',
		'SKernel',
		'SUnit',
		'WindowsSystem'
	]
	#classes : [
		'ABC',
		'BITMAP',
		'BITMAPFILEHEADER',
		'BitmapHeaderStructure',
		'BITMAPINFO',
		'BITMAPINFOHEADER',
		'BITMAPV4HEADER',
		'BITMAPV5HEADER',
		'CIEXYZ',
		'CIEXYZTRIPLE',
		'COLORREF',
		'CommonDeviceContext',
		'DEV_BROADCAST_HDR',
		'DeviceContext',
		'DeviceContextTest',
		'DEVMODE',
		'DEVNAMES',
		'DISPLAY_DEVICE',
		'DrawerTest',
		'EXTLOGPEN',
		'FXPT2DOT30',
		'GDIBitmap',
		'GDIBitmapTest',
		'GDIBrush',
		'GDIDLL',
		'GDIDLLTest',
		'GDIDrawer',
		'GDIDrawerTest',
		'GDIFont',
		'GDIFontTest',
		'GDILogicalObject',
		'GDIObject',
		'GDIObjectTest',
		'GDIPalette',
		'GDIPen',
		'GLYPHSET',
		'ICONINFO',
		'ICONINFOEX',
		'LOGBRUSH',
		'LOGFONT',
		'LOGPALETTE',
		'LOGPEN',
		'MONITORINFOEX',
		'PALETTEENTRY',
		'POINT',
		'RECT',
		'RGBQUAD',
		'Screen',
		'ShcoreDLL',
		'SIZE',
		'TEXTMETRIC',
		'VirtualScreen',
		'WCRANGE'
	]
}

