"
    Copyright (c) 2020 Aucerna.
    See (MIT) license in root directory.
"

Package { #name : #Intel,
	#classes : [
		'ABI',
		'InstructionEncoder',
		'InstructionPrefix',
		'InstructionSpec',
		'ISAImmediate',
		'ISAInstruction',
		'ISAOperand',
		'ISAOperandType',
		'LegacyPrefix',
		'MemoryOperand',
		'OperandEncoding',
		'Register',
		'REXPrefix',
		'SegmentPrefix',
		'VEXPrefix',
		'X64ABI',
		'X86ABI'
	]
}

