Package { #name : #SMark,
	#classes : [
		'ReBenchHarness',
		'ReBenchHarnessArgumentParser',
		'ReBenchReporter',
		'SMarkAutosizeRunner',
		'SMarkBeeRunner',
		'SMarkCogRunner',
		'SMarkHarness',
		'SMarkHarnessArgumentParser',
		'SMarkProfileRunner',
		'SMarkReporter',
		'SMarkResult',
		'SMarkRunner',
		'SMarkSimpleStatisticsReporter',
		'SMarkSuite',
		'SMarkTimer',
		'SMarkTransporter',
		'SMarkWeakScalingRunner',
		'SMarkWeakScalingRunnerExecutor'
	]
}

